diff --git a/.codeclimate.yml b/.codeclimate.yml
index e69de29..2e97d7f 100644
--- a/.codeclimate.yml
+++ b/.codeclimate.yml
@@ -0,0 +1,8 @@
+---
+engines:
+  fixme:
+    enabled: true
+ratings:
+  paths: []
+exclude_paths:
+- test/
