language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-*
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-*

script:
  - dotnet --verbose build ./*/*/project.json
  - dotnet --verbose test ./test/*/project.json
  - popd